/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificateInterface extends Interface {
    getFunction(nameOrSignature: "certificates" | "issueCertificate" | "owner" | "verifyCertificate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateIssued"): EventFragment;

    encodeFunctionData(functionFragment: 'certificates', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'issueCertificate', values: [BytesLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyCertificate', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'certificates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCertificate', data: BytesLike): Result;
  }

  
    export namespace CertificateIssuedEvent {
      export type InputTuple = [certificateHash: BytesLike, studentName: string, issueDate: string];
      export type OutputTuple = [certificateHash: string, studentName: string, issueDate: string];
      export interface OutputObject {certificateHash: string, studentName: string, issueDate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Certificate extends BaseContract {
    
    connect(runner?: ContractRunner | null): Certificate;
    waitForDeployment(): Promise<this>;

    interface: CertificateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    certificates: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, boolean] & {studentName: string, courseName: string, issueDate: string, isIssued: boolean }],
      'view'
    >
    

    
    issueCertificate: TypedContractMethod<
      [_hash: BytesLike, _studentName: string, _courseName: string, _issueDate: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyCertificate: TypedContractMethod<
      [_hash: BytesLike, ],
      [[boolean, string, string, string] & {isIssued: boolean, studentName: string, courseName: string, issueDate: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'certificates'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, boolean] & {studentName: string, courseName: string, issueDate: string, isIssued: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'issueCertificate'): TypedContractMethod<
      [_hash: BytesLike, _studentName: string, _courseName: string, _issueDate: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCertificate'): TypedContractMethod<
      [_hash: BytesLike, ],
      [[boolean, string, string, string] & {isIssued: boolean, studentName: string, courseName: string, issueDate: string }],
      'view'
    >;

    getEvent(key: 'CertificateIssued'): TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;

    filters: {
      
      'CertificateIssued(bytes32,string,string)': TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
      CertificateIssued: TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
    
    };
  }