/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Certificate } from './Certificate.js';
export * as factories from './factories/index.js';
export { Certificate__factory } from './factories/Certificate__factory.js';